// Leetcode: https://leetcode.com/problems/find-the-difference/description/
// Given strings s and t (lowercase letters), t is generated by shuffling s and adding a letter
// at a random index. Find the letter that was added in t.

// Brute Force: For every char in t, scan s to find it's count. O(m*n) time.
// Better: Count chars in s and t, then compare char counts. O(m+n) time.

#include <string>
#include <iostream>
#include <assert.h>

// Accepted. 3ms. Beats 55.98% of submissions, ties 44.02% of submissions.
class Solution {
public:
    char findTheDifference(const std::string& s, const std::string& t) {
        int s_counts[26] = {0};
        int t_counts[26] = {0};

        for (auto ch : s) { ++s_counts[ch-'a']; }
        for (auto ch : t) { ++t_counts[ch-'a']; }

        for (int i = 0; i < 26; ++i) {
            if (t_counts[i] == s_counts[i] + 1) { return char('a' + i); }
        }
        return '\0';
    }
};

int main(int argc, char** argv) {
    std::cout << argv[0] + 2 << "...OK!" << std::endl;
    return 0;
}
